### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by JMaravalhasSilva** [xiuheng-wang/awesome-hyperspectral-image-unmixing#3]
The following techniques mentioned in the readme file, under the section "Classic unmixing methods", have broken links:

7. Fully constrained least squares spectral unmixing by simplex projection.
8. A distance geometric framework for nonlinear hyperspectral unmixing.

Fortunately, everything is still available on the internet archive:
https://web.archive.org/web/20221207130159/https://sites.google.com/site/robheylenresearch/code

**Comment by xiuheng-wang** [comment]
Thank you for bringing this to our attention. 
We have updated the README file with the new links to ensure smooth access for users. 
We appreciate again for your support.
